name: Build and deploy Python app to Azure Web App - projcloud

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate  # Utilisation du point pour activer l'environnement virtuel

      - name: Install dependencies
        run: |
          . venv/bin/activate
          pip install -r backend/requirements.txt  # Assurez-vous que le chemin est correct

      - name: Install pytest
        run: |
          . venv/bin/activate
          pip install pytest  # Assurez-vous que pytest est installé

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest  # Remplacez par votre commande de tests si nécessaire

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "venv/*"  # Exclure le dossier venv

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Ceci est requis pour demander le JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68CF53B7F49E46CE8B3932358600115D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B17337A979304EC2BBC1E79A094BA6B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_208C2251B9374253BCA769959DC7E62E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'projcloud'
          slot-name: 'Production'
