name: Build and deploy Python app to Azure Web App - projetcl

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r backend/requirements.txt  # Si requirements.txt est dans le dossier backend

      # Optionnel : Ajouter une étape pour exécuter des tests (comme PyTest si vous en avez)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "venv/*"  # Exclure le dossier venv

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #Ceci est requis pour demander le JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C30D3FD3FB454C24A9F0E86850605D1E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_49D8C680677A48A4A0A9EAA5EBA40129 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CDAC364777E1464D9C90F29E134C38A9 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'projetcl'
          slot-name: 'Production'
